# version: "3.9"
services:
  web-server:
    build: .
    image: concept/node
    container_name: web-server
    ports:
      - "3000:3000"
    environment: 
      PORT: 3000
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: database 
    ports:
      - "1433:1433"
    environment:
      MSSQL_PID: "Developer"
      SA_PASSWORD: "CTHM@projeto2021"
      ACCEPT_EULA: "Y"